on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@master
        with:
          dotnet-version: 3.1.x
      - run: |
          dotnet publish -c Release
          if ($LASTEXITCODE -ne 0) { exit 1 }
          7z a release.zip .\bin\Release\netcoreapp3.1\publish\* .\LICENSE
      - if: github.ref == 'refs/heads/master'
        run: |
          cmd /c "git fetch --tags --unshallow 2>&1"
          mkdir -Force ~\.ssh
          [IO.File]::WriteAllBytes( `
              "$Env:USERPROFILE\.ssh\id_ed25519", `
              [Convert]::FromBase64String("${{ secrets.DEPLOYKEY }}"))
          cmd /c 'ssh-keyscan web.sourceforge.net > "%USERPROFILE%\.ssh\known_hosts" 2>nul'
          cmd /c "scp release.zip ddosolitary@web.sourceforge.net:/home/project-web/ddosolitary-builds/htdocs/Wenku8ProgressRecorder/Wenku8ProgressRecorder-r$(git rev-list --count HEAD).zip 2>&1"
          if ($LASTEXITCODE -ne 0) { exit 1 }
